### ISSUE TITLE
Ensure valid configuration

### ISSUE THREAD

**Issue by tommasobertoni** [artiso-solutions/CoVoX#48]
Provide specific model validation for the `Configuration` instance.

```yaml
Configuration:

  # Not null
  azureConfiguration:
    # Not null or empty
    subscriptionKey:
    # Not null or empty
    region:

  # 0 < value <= 1
  matchingThreshold:

  # Not null or empty
  # Must contain valid languages
  inputLanguages:

  hotWords:
```

Hint: list available "languages"
```csharp
var cultures = CultureInfo.GetCultures(CultureTypes.AllCultures).Select(c => c.Name);
```
